atomsci/ddm/utils/curate_data.py

As Amanda suggested in the Best Practice:
_This function should be updated / adapted to be used before aggregate_assay_data() to ID disparate measurements that should be dropped, but not go through with averaging and returning a new DF_
I added a parameter **rm_duplicate_only** to function **average_and_remove_duplicates**, so that we can just remove **bad** duplicates without averaging the rest. The resulting table can be fed into the function **aggregate_assay_data**.

add the option to only remove bad duplicate but not average

---

atomsci/ddm/pipeline/compare_models.py
atomsci/ddm/pipeline/model_datasets.py
atomsci/ddm/pipeline/parameter_parser.py
atomsci/ddm/pipeline/splitting.py
atomsci/ddm/utils/hyperparam_search_wrapper.py

- `compare_models.py`:
- `get_best_models_info`: work with shortlists
- `get_multitask_perf_from_tracker`: add 'features' column
- `parameter_parser.py`: change default of rerun flag to 'True' so no one's pipelines are changed
- `splitting.py`: cast compound_id column as strings
- `hyperparam_search_wrapper.py`:
- `generate_param_combos`: allow for iterating over computed descriptor types
- `generate_assay_list`, `generate_split_shortlist`, `submit_jobs`, `get_shortlist_df`: add response_col and collection_name into shortlist options
- `return_split_uuid_file`, `generate_split_shortlist_file`, `main`: run shortlist splitting from filesystem without referring to or saving to datastore
- `main`: add prediction_type to keep_params to deal with uncertainty of graphconv models (no unc in gc …

Amanda dev

---

README.md
atomsci/ddm/docs/PARAMETERS.md
atomsci/ddm/pipeline/parameter_parser.py
atomsci/ddm/utils/hyperparam_search_wrapper.py

1. Fix a bug for uncertainty setting for classification models. 
2. Update the code to save performance (R2, RMS/AUC, Accuracy) for train, valid, and test set.

update HyperOpt code

---

atomsci/ddm/pipeline/ave_splitter.py
atomsci/ddm/pipeline/chem_diversity.py
atomsci/ddm/pipeline/compare_models.py
atomsci/ddm/pipeline/dist_metrics.py
atomsci/ddm/pipeline/diversity_plots.py
atomsci/ddm/pipeline/featurization.py
atomsci/ddm/pipeline/model_pipeline.py
atomsci/ddm/pipeline/perf_plots.py
atomsci/ddm/pipeline/temporal_splitter.py
atomsci/ddm/utils/rdkit_easy.py
atomsci/ddm/utils/struct_utils.py

Added and corrected doc strings for modules, classes and functions.

Doc strings

---

atomsci/ddm/pipeline/model_wrapper.py
atomsci/ddm/test/integrative/ad_index/test_ad_index.py

1) fixed test_ad_index.py test case 2) convert CUDA tensor to Numpy

1) fixed test_ad_index.py test case 2) convert CUDA tensor to Numpy

---

atomsci/ddm/pipeline/parameter_parser.py
atomsci/ddm/test/integrative/delaney_XGB/config_delaney_fit_XGB.json
atomsci/ddm/test/integrative/delaney_XGB/config_delaney_predict_XGB.json
atomsci/ddm/test/integrative/delaney_XGB/download_dataset.sh
atomsci/ddm/test/integrative/delaney_XGB/pytest_slurm.sh
atomsci/ddm/test/integrative/delaney_XGB/test_delany_XGB.py

Sets uncertainty to false when xgboost is chosen

XGB doesn't support uncertainty.

---

atomsci/ddm/pipeline/model_wrapper.py
atomsci/ddm/test/integrative/delaney_Panel/jsons/config_delaney_fit_rf_3fold_cv.json
atomsci/ddm/test/integrative/delaney_Panel/jsons/config_delaney_fit_xgb_3fold_cv.json
atomsci/ddm/test/integrative/delaney_Panel/test_delaney_panel.py

Verified 
% pytest test_delaney_panel.py::test_reg_config_delaney_fit_RF_3fold

remove 'restore'. deepchem doesn't support in 2.5

---

atomsci/ddm/examples/BSEP/README.md
atomsci/ddm/examples/BSEP/data/ChEMBL25_BSEP_curated_data.csv
atomsci/ddm/examples/BSEP/data/ChEMBL25_BSEP_test_data.csv
atomsci/ddm/examples/BSEP/data/small_test_data.csv
atomsci/ddm/examples/BSEP/predict_bsep_inhibition.py
atomsci/ddm/pipeline/model_pipeline.py
atomsci/ddm/pipeline/predict_from_model.py
atomsci/ddm/test/integrative/foreign_model/pytest_slurm.sh

I updated the BSEP example to work with the AD index & 1.3 updates. I also created a test for foreign models with and without ADI calculation.

Test foreign model

---

atomsci/ddm/pipeline/model_pipeline.py

correct AD distance parameter

---

atomsci/ddm/test/integrative/foreign_model/pytest_slurm.sh
atomsci/ddm/test/integrative/foreign_model/test_foreign_model.py

changed the test shell script to pytest

changed the test shell script to pytest

---

atomsci/ddm/pipeline/feature_importance.py
atomsci/ddm/utils/rdkit_easy.py

I checked in a notebook, data_science/notebooks/test_feature_importance.ipynb, that exercises all the public functions in the new feature importance module. I have not yet tested it with XGBoost models or any of the new DeepChem models.

Feature importance module.

---

atomsci/ddm/docs/PARAMETERS.md
atomsci/ddm/pipeline/compare_models.py
atomsci/ddm/pipeline/model_wrapper.py
atomsci/ddm/pipeline/parameter_parser.py
atomsci/ddm/test/integrative/dc_models/test_dc_models.py

Feature dc models

---

atomsci/ddm/pipeline/model_datasets.py
atomsci/ddm/test/unit/test_model_dataset.py

- Implemented the code
- Provided a test `test_model_dataset.py::test_load_presplit_dataset`

added the handle when can't find previous split uuid

---

atomsci/ddm/pipeline/model_wrapper.py
atomsci/ddm/pipeline/splitting.py
atomsci/ddm/test/integrative/compare_models/test_filesystem_perf_results.py
atomsci/ddm/test/integrative/random_seed/reg_config_delaney_fit_RF_mordred_filtered.json
atomsci/ddm/test/integrative/random_seed/test_random_seed.py

remove any hard coded random seeds and calls to np.random.seed.

Bug rf randomness

---

atomsci/ddm/docs/PARAMETERS.md
atomsci/ddm/pipeline/MultitaskScaffoldSplit.py
atomsci/ddm/pipeline/parameter_parser.py
atomsci/ddm/pipeline/splitting.py
atomsci/ddm/test/integrative/multitask_split/multitask_config.json
atomsci/ddm/test/integrative/multitask_split/multitask_config_split_only.json
atomsci/ddm/test/integrative/multitask_split/test_split.py
atomsci/ddm/utils/compare_splits_plots.py

Examples can be found here: atomsci/ddm/test/integrative/multitask_split

added multitaskscaffold split to the pipeline

---

atomsci/ddm/pipeline/diversity_plots.py
atomsci/ddm/utils/hyperparam_search_wrapper.py

Update `plot_tani_dist_distr()` and hyperparameter shortlist splitting code to include fingerprint splitter.

Perf plots

---

atomsci/ddm/test/integrative/multitask_split/test_split.py

Change the test to match new argument names.

arguments name changed

---

atomsci/ddm/pipeline/model_pipeline.py
atomsci/ddm/test/integrative/dc_models/test_retrain_dc_models.py
atomsci/ddm/test/integrative/delaney_Panel/test_delaney_panel.py
atomsci/ddm/test/integrative/early_stopping_tests/test_kfold_split.py
atomsci/ddm/test/integrative/hyperparam_search/test_hyperparam.py
atomsci/ddm/test/integrative/shortlist_test/test_shortlist.py
atomsci/ddm/test/unit/test_LCTimerIterator.py
atomsci/ddm/test/unit/test_model_version.py
atomsci/ddm/test/unit/test_num_trainable_params.py
atomsci/ddm/utils/model_retrain.py
atomsci/ddm/utils/model_version_utils.py
install_ampl_env.sh
set_dgl_env.sh

- added the check in the tests to see if it's in LC environment. 
- added an util to compare current running AMPL version with the input model tar file to see if they are compatible.
- added tests test_num_trainable_params.py::test_versions_not_compatible and test_num_trainable_params.py::test_versions_compatible()

added code to check versions compatible or not. added tests

---

atomsci/ddm/pipeline/model_wrapper.py

Use separate model.restore() function in order to force a GPU trained model to work on a CPU machine

create dc_torch_restore() fcn for cpu compatibility

---

atomsci/ddm/pipeline/featurization.py
atomsci/ddm/test/unit/test_make_weights.py

There was a mistake in the make_weights function that created incorrect weights. I added a test case. This hasn't been run against the full test panel.

Bug make weights

---

.github/workflows/pkg_conda_pytest_integrative.yml
.github/workflows/pkg_conda_pytest_unit.yml
atomsci/ddm/test/integrative/dc_models/test_dc_models.py
atomsci/ddm/test/integrative/dc_models/test_retrain_dc_models.py
atomsci/ddm/test/integrative/delaney_Panel/test_delaney_panel.py
atomsci/ddm/test/integrative/hybrid/test_hybrid.py
atomsci/ddm/test/integrative/hyperparam_search/test_hyperparam.py
atomsci/ddm/test/integrative/integrative_batch_tests.sh
atomsci/ddm/test/integrative/maestro/test_maestro.py
atomsci/ddm/test/integrative/wenzel_NN/test_wenzel_NN.py
atomsci/ddm/test/unit/test_LCTimerIterator.py
atomsci/ddm/test/unit/test_model_version.py
atomsci/ddm/test/unit/test_num_trainable_params.py
atomsci/ddm/test/unit/test_param_parser.py
atomsci/ddm/test/unit/test_prediction_order.py

- setup CI workflow pipeline
- upon push on certain branches, will kick start the test job run on `unit` and `integrative` directories
- only files with .py, .sh, .yml apply

Setup ci workflow

---

atomsci/ddm/pipeline/compare_models.py
atomsci/ddm/pipeline/hyper_perf_plots.py

I made small changes to `compare_models.get_filesystem_perf_results()` and `hyper_perf_plots` to allow for
1. more minimal examples to be used with the code
2. multiclass classification models to be used with the code

Multiclass class

---

atomsci/ddm/pipeline/compare_models.py
atomsci/ddm/pipeline/model_pipeline.py
atomsci/ddm/pipeline/model_tracker.py
atomsci/ddm/test/integrative/dc_models/test_retrain_dc_models.py
atomsci/ddm/test/integrative/shortlist_test/test_shortlist.py
atomsci/ddm/test/integrative/wenzel_NN/test_wenzel_NN.py
atomsci/ddm/test/unit/test_file_utils.py
atomsci/ddm/utils/datastore_functions.py
atomsci/ddm/utils/file_utils.py
atomsci/ddm/utils/model_retrain.py
atomsci/ddm/utils/model_version_utils.py

- Created a safe extract utility and replaced the existing usage of extractall() with safe_extract().

added safe extract

---

atomsci/ddm/pipeline/parameter_parser.py
atomsci/ddm/utils/many_to_one.py

Updating error messages and comments.

update comments and error messages

---

atomsci/ddm/test/README.md

Added README for AMP tests. Provided info on special resources used in some tests.

Test readme doc

---

README.md
atomsci/ddm/pipeline/parameter_parser.py
pip/requirements.txt

- Updated the install to use python 3.9.x
- Updated related docs.

Ampl160 py39

---

README.md
pip/readthedocs_requirements.txt

Updated readme per https://github.com/ATOMScience-org/AMPL/issues/198
- added examples

Update readme example

---

atomsci/ddm/test/unit/test_model_file_reader.py
atomsci/ddm/utils/model_file_reader.py

- Use  tarfile.open() instead of tempfile.mkdtemp() 
- Added a function to process multiple tar.gz files

updated the model file reader

---

README.md

Replaced all lowercase letters with uppercase letters in the anchor tags in README.md.

Updated anchor tags in README.md

---

atomsci/ddm/docs/.readthedocs.yaml

Readthedocs config v2

---

atomsci/ddm/examples/tutorials2023/02_data_curation.ipynb

Hi @stewarthe6 I made some edits to the tutorial. I think it's simple and concise which is perfect, but I also think it's useful to compare the original to what changes are happening at every step, so I added a few things that make that clear.

Setup tutorials akp

---

README.md

- Use summary, details to hide some sections
- Use subscripts for smaller fonts

Update 160 readme

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

New pages on Contribution guidelines and code of conduct.

Feature additional docs

---

atomsci/ddm/examples/tutorials2023/01_install_from_docker.md

I think some elaboration on what the 'workspace folder' is would be helpful.

Minor edits to Tutorial 1.

---

atomsci/ddm/examples/tutorials2023/06_hyperopt.ipynb

Modified text to remove some formatting of key works like hyperparameters and Bayesian optimization, changed the wording around links, added description of some important directories that are created, and added more sections

Changes to the text of the notebook

---

atomsci/ddm/examples/tutorials/03_perform_a_split.ipynb

Hi, I updated the file path printed in the 3rd code cell to change it from  `…/examples/tutorials`  to `…/examples/tutorials2023`.

updated file path

---

README.md
pip/mchip_requirements.txt

I created a fresh environment and double checked these instructions, making a few edits and streamlining the instructions. They work fine.

update M chip instructions

---

atomsci/ddm/pipeline/model_wrapper.py
atomsci/ddm/test/unit/test_gpytorch_wrapper.py

This is work completed from the UD-ATOM Hackathon. The purpose is to integrate GPyTorch functionality into AMPL.

Integrate gpytorch wrapper

---

atomsci/ddm/pipeline/compare_models.py
atomsci/ddm/pipeline/featurization.py
atomsci/ddm/pipeline/parameter_parser.py
atomsci/ddm/pipeline/perf_data.py
atomsci/ddm/pipeline/transformations.py
atomsci/ddm/utils/data_curation_functions.py
atomsci/ddm/utils/datastore_functions.py
atomsci/ddm/utils/model_file_reader.py
atomsci/ddm/utils/struct_utils.py

These are small changes from lint_finds that I split up into 4 commits:
1. update isinstance(x) back to type(x) 
2. delete unused lines and unused variable assignments (possibly unsafe, I can revert this commit)
3. fix some imports and associated function calls
4. remove "==True" or "is True" (and false) redundancies

Akp lint fixes

---

.github/workflows/build.yml
Makefile
pip/cpu_requirements.txt
pip/docker_requirements.txt
pip/mchip_requirements.txt

- Fix the docker build for arm chip.
- Change the build.yml condition to generate the desired tags for production.

Update build ci

---

atomsci/ddm/pipeline/model_pipeline.py
atomsci/ddm/pipeline/predict_from_model.py
atomsci/ddm/test/unit/test_AD.py

Fixed some +1 errors in AD calculation and created a test. Also calc_AD_kmean_dist now returns indexes for the nearest neighbors for each query. The function predict_from_model_file now has an option to append columns that lists the compound IDs of the nearest neighbors from the training set.

AD improvements

---

atomsci/ddm/test/integrative/compare_models/jsons/reg_config_delaney_fit_XGB_mordred_filtered.json
atomsci/ddm/test/integrative/compare_models/test_filesystem_perf_results.py
atomsci/ddm/test/integrative/hyperopt/H1_RF_hyperopt.json
atomsci/ddm/test/unit/test_param_parser.py

Added tests, updated the test json for the new parameters.

Sparsity test

---

.github/workflows/pytest.yml
README.md
atomsci/ddm/docs/source/conf.py
atomsci/ddm/docs/source/tutorials/05_hyperopt.rst
atomsci/ddm/docs/source/tutorials/ampl_tutorials_intro.rst
atomsci/ddm/pipeline/compare_models.py
atomsci/ddm/pipeline/feature_importance.py
atomsci/ddm/pipeline/parameter_parser.py
atomsci/ddm/pipeline/perf_plots.py
atomsci/ddm/utils/datastore_functions.py
atomsci/ddm/utils/hyperparam_search_wrapper.py
atomsci/ddm/utils/model_file_reader.py

- Updated the doc config for 1.7.0
- Added the links to video tutorials.
- Fixed some docstrings

Video announcement
