ATOMScience-org/AMPL

atomsci/ddm/pipeline/compare_models.py
atomsci/ddm/pipeline/featurization.py
atomsci/ddm/pipeline/model_pipeline.py
atomsci/ddm/pipeline/transformations.py

Functions in compare_model.py:
1. get_summary_perf_tables, use result directory instead of collection names and bucket
2. get_best_models_info, use result directory instead of collection names
3. get_best_perf_table, use result directory instead of collection names
4. get_tarball_perf_table, add this new function to directly extract model performance from a model tarball.
Functions in model_pipeline.py:
1. retrain_model, use result directory instead of collection names

adapt functions for non-LC systems.

---

atomsci/ddm/pipeline/model_pipeline.py

Updating the way we determine the version of ampl to account for switching github branches, and also account for normal installation where the package is installed in site-packages

update the way we decide the ampl_version

---

atomsci/ddm/pipeline/compare_models.py
atomsci/ddm/utils/model_retrain.py

Sometimes the dataset key saved in the json file is no longer reachable either because the file moved or because the original dataset was in someones private folders. This allows you to retrain using the same parameters, but specify a new dataset key.

Retrain with new datasetkey

---

atomsci/ddm/utils/hyperparam_search_wrapper.py

I think I introduced a bug where the split_uuid parameter was being filtered out by parse_params in hyperparam_search_wrapper which meant that you could never reuse a previous split. This adds the 'split_uuid' to the filter.
Run tests here: atomsci/ddm/test/integrative/hyperparam_search to verify the fix.

added previously_split and split_uuid to param filter

---

atomsci/ddm/pipeline/model_pipeline.py
atomsci/ddm/pipeline/predict_from_model.py
atomsci/ddm/test/unit/test_predition_order.py

Turns out that using df.merge or df.join will shuffle rows. This method of reogranizing rows replaces ids with integers, performs the predictions, fills in any missing ids, sorts by integers to recover the original order, then replaces the integers with the original ids

Return predictions in input order.

---

atomsci/ddm/pipeline/model_pipeline.py

predict_on_dataframe and predict_on_smiles expect a column called 'pred', 'std', and sometimes 'prob'. Calling predict_full_dataset prepends the response col to the 'pred' and 'std' and 'prob' columns causing the bug. Now 'predict_on_dataframe' and 'predict_on_smiles' remove the response_col prefix before returning the result data frame

No pred col bug

---

atomsci/ddm/test/integrative/shortlist_test/test_shortlist_RF-NN-XG_hyperconfig.json

Some ATOM users don't have access to asccasc. Removing that line allows AMPL to use the default lc_account instead.

remove the lc_account 'asccasc'

---

README.md
atomsci/ddm/pipeline/model_datasets.py
atomsci/ddm/pipeline/model_wrapper.py
atomsci/ddm/pipeline/predict_from_model.py
atomsci/ddm/utils/datastore_functions.py
atomsci/ddm/utils/hyperparam_search_wrapper.py

In this pull request I am doing 3 main things:
- Updated hyperparameter search wrapper to change the order of the loop: instead of filtering all jobs first, I filter them one at a time and then submit. This is more stable (especially when querying the MT for 1000's of jobs) and allows for jobs to be submitted faster.
- Found a few hanging open files that I've updated the code to explicitly close them
- When a model is trained elsewhere, the ADI calculation looks in the original location for the original data. Here I extend the predict_from_model_file() function to allow for intake of a new path to the external training data. Then the dataset_key field in params is updated and the ADI calculation is able to proceed. In order for this to work, the original column names must be passed for …

hp search wrapper, misc open files, extend ADI capabilities

---

atomsci/ddm/utils/rdkit_easy.py

I've added an option to embed an image into a standalone HTML file. This simplifies sharing an interactive layout (with molecule images) with collaborators who may not be coders. It will create large files since each image is embedded, so I set the default to False and print a warning.

Rdkit easy update html

---

atomsci/ddm/pipeline/diversity_plots.py

A quick update to allow different ECFP radii when plotting tanimoto distances. I read that 4 or 6 is better than our default (2) for structure comparisons.

add radius option to tanimoto dist plot

---

conda/pip_requirements.txt

Added bokeh 2.3.3 to the pip install list.
To verify that it doesn't break other code and packages:
- create a new atomsci environment:
$ conda create -y -n atomsci_bokeh --file conda_package_list.txt
$ conda activate atomsci_bokeh
$ pip install -r pip_requirements.txt
Run test code:
$ cd atomsci/ddm/test/integrative/dataset_hash
$ pytest test_hash_checksum.py::test_uses_same_training_data_by_tars_delaney_train_NN 
$ pytest test_hash_checksum.py::test_uses_same_training_data_by_tars_nn_ecfp 
$ pytest test_hash_checksum.py::test_uses_same_training_data_not_equals_by_tars

add bokeh to the pip install list

---

atomsci/ddm/pipeline/model_wrapper.py
atomsci/ddm/pipeline/parameter_parser.py
atomsci/ddm/test/unit/test_model_wrapper.py

DeepChem changed the Multitask models over to Pytorch. As a result the DCNNModelWrapper can't wrap both the GraphConv (keras) and the Multitask (Pytorch) models anymore, because of the copy and saving functions. the DCNNModelWrapper is removed and split into 2 classes, GraphConvDCModelWrapper and MultitaskDCModelWrapper. These inherit the KerasDeepChemModelWrapper and PytorchDeepChemModelWrapper respectively.

Bug dc261 restore

---

atomsci/ddm/pipeline/predict_from_model.py

The functions predict_from_tracker_model and predict_from_model_file are missing a description for the argument is_featurized. I added a description for the argument to both block comments within the function.

Updated comments in predict_from_model.py

---

atomsci/ddm/pipeline/MultitaskScaffoldSplit.py
atomsci/ddm/pipeline/model_datasets.py
atomsci/ddm/pipeline/splitting.py
atomsci/ddm/utils/model_version_utils.py

This branch replaces all uses of the deepchem DiskDataset class with NumpyDataset. There was never a good reason to use DiskDataset because the sizes of datasets we train models on were never big enough to benefit from sharding. In addition, the way we used DiskDataset (by calling the static from_numpy method) automatically put everything in one shard, so we've been dealing with the extra file I/O overhead without any gain. Using NumpyDataset should make model training and inference faster, and eliminate the temporary files that were generated every time the GMD loop made predictions from an AMPL model.
This branch also includes a fix to model_version_utils.get_ampl_version_from_model to read the model_metadata.json from a tarfile stream, without having to untar the model tarball first. …

Replace dc.data.DiskDataset with NumpyDataset and otherwise reduce creation of temp files

---

atomsci/ddm/examples/tutorials/AMPL_FNL_Wrshp2_1.ipynb
atomsci/ddm/examples/tutorials/README.md

- [atomsci/ddm/examples/tutorials/README.md](https://github.com/ATOMScience-org/AMPL/compare/fix_tutorial_links?expand=1#diff-1a85e480e0db3d8fd21d99f26f37aa438ba9cd0f4650335c0e0fca3d5e009b70) 
- removed tutorial 13(notebook doesn't exist)
- [atomsci/ddm/examples/tutorials/AMPL_FNL_Wrshp2_1.ipynb](https://github.com/ATOMScience-org/AMPL/compare/fix_tutorial_links?expand=1#diff-82cdfd6a17e50c610a6ff07744c0f01b78d077cedb141f6d140a4aa949b94edd)
- Updated the image links. For some reasons, two images in this notebook, show as invalid links from github. But from LC jupyter, the image links display fine.

Fix tutorial links

---

atomsci/ddm/utils/curate_data.py
atomsci/ddm/utils/struct_utils.py

Fixed curate_data.freq_table so it won't fail when column selected contains NaNs.
Added a new optional boolean argument to base_smiles_from_smiles and rdkit_smiles_from_smiles, useCanonicalTautomers. If set True, the function will perform the additional standardization step of mapping structures to their "canonical" tautomers. The default is False to preserve compatibility with datasets generated previously.

Utils function fixes and enhancements

---

atomsci/ddm/pipeline/featurization.py

Otherwise, they might be treated as ints and merging/inclusion/comparisons will not work correctly

Compound IDs should always be explicitly treated as strings. 

---

README.md
atomsci/ddm/docs/source/guide/install.rst

Removed `--no-use-pep517` from README. Was removed from `1.6.0`. Since most users refer to the `master` branch, remove it till `1.6.0` is out.

removed  --no-use-pep517 from README

---

atomsci/ddm/docs/.readthedocs.yaml

Added  .readthedocs.yaml due to their changes:
> In line with [our deprecation plans for builds without a configuration file](https://blog.readthedocs.com/migrate-configuration-v2/), projects will be required to specify a configuration file to continue building their documentation starting September 25th.

defined .readthedocs.yaml for v2

---

atomsci/ddm/pipeline/diversity_plots.py
atomsci/ddm/pipeline/featurization.py
atomsci/ddm/pipeline/model_datasets.py
atomsci/ddm/utils/model_retrain.py
atomsci/ddm/utils/rdkit_easy.py

In this branch I did the following (sorry - I accidentally merged two branches before requesting pulls) 
4 commits in model_dataset.py from bug #237:
- create a check to see if all the smiles in a dataset are represented in the prefeaturized data
- if not, raise assertion error
- if so, allow
- raise the error up to get_featurized_data()
1 commit in diversity_plots.py: 
- I updated diversity_plots to allow a user-specified color palette and increase the resolution of the figure. No behavior will change unless you want to pass a color palette.
2 commits in featurization.py:
- reduce dataframe fragmentation by updating how the dataframe is constructed
- respect the original index of the file
1 commit in model_retrain.py:
- add a check so that if a model was originally trained and saved to …

Prefeat smiles check

---

atomsci/ddm/pipeline/featurization.py
atomsci/ddm/pipeline/model_pipeline.py

Place holder compound ids were ints when they should be strings.

Bug moe pred

---

atomsci/ddm/pipeline/featurization.py
atomsci/ddm/test/integrative/transfser_learning/test_embedding_feature.py

Transfer learning with a base model using mordred_filtered features was producing nan predictions. Dataset preparation skipped a set that set nans in mordred features, which is totally normal, to zeros.

need to transform dataset before using it

---

atomsci/ddm/pipeline/perf_plots.py
atomsci/ddm/utils/compare_splits_plots.py

I updated 
- compare_splits tanimoto distance histograms to be matplotlib axes instead of seaborn facet grids
- perf_plots now have two more plots to plot predicted_vs_actual from a dataframe or from a model tarball
- still needs the comparable plots for classification models (#254)

Perf plots

---

atomsci/ddm/pipeline/chem_diversity.py
atomsci/ddm/pipeline/compare_models.py
atomsci/ddm/pipeline/featurization.py
atomsci/ddm/pipeline/parameter_parser.py
atomsci/ddm/utils/hyperparam_search_wrapper.py
atomsci/ddm/utils/patch_model_dataset_key.py
atomsci/ddm/utils/rdkit_easy.py

- Add full support for all XGBoost model parameters, including hyperopt searches.
- Add split_strategy output column to compare_models.get_filesystem_perf_results.
- Fix bug in setting response column weights to make it consistent across featurizers.
- Fix error handling in rdkit_easy.mol_to_html to return empty string rather than None.
- Only import datastore_functions module in functions that require it, so that atomsci-clients isn't required.
- Add script for patching model tarballs to point to local copy of training data (needed for AD computation).

Miscellaneous changes for 1.6.0

---

atomsci/ddm/utils/split_response_dist_plots.py
pip/readthedocs_requirements.txt

- Added torch in the readthedocs pip requirements to see if that will fix the issue of parameter_parser module not showing.
- Added docstring line breaks for split_response_dist_plots.py.

try to fix the issue with parameter_parser module not showing

---

atomsci/ddm/pipeline/MultitaskScaffoldSplit.py
atomsci/ddm/pipeline/parameter_parser.py
atomsci/ddm/pipeline/splitting.py
atomsci/ddm/utils/split_response_dist_plots.py

Added a new MTSS parameter and a fitness function term to allow optimizing a scaffold split so that the response value distributions in the training, validation and test sets are as similar as possible. This addresses a common problem with scaffold splits, especially of small datasets, where the validation and/or test set performance metrics look bad because a model wasn't trained on the full range of values found in the test sets.

Optimize MTSS split for similarity of response value distributions across split subsets

---

atomsci/ddm/pipeline/compare_models.py
atomsci/ddm/pipeline/model_pipeline.py
atomsci/ddm/pipeline/parameter_parser.py

I fleshed out the capabilities of ampl to handle the `balancing` weights transformer by including the information in the `model_metadata` (in the training dataset part along with `feature_transform_type`), and including `weight_transform_type` (along with `split_uuid`) in the `compare_models.get_filesystem_perf_results()` dataframe. 
After doing this, I also had to expand the parameter parser to accept `None` and `'None'` as options for the `weight_transform_type` because previously the only option in the list was `'balancing'` and this threw errors when trying to predict from a model with 'None' transform type (I'm not sure where the string None came from).
I can still get through all the tutorials without errors so I think this is OK to merge but would like a second pair of eyes!

Weight transform akp

---

.github/workflows/pytest.yml
atomsci/ddm/test/integrative/dc_models/test_dc_models.py
atomsci/ddm/test/integrative/integrative_batch_chunk_tests
atomsci/ddm/test/integrative/wenzel_NN/test_wenzel_NN.py
pip/ci_requirements.txt

This adds 2 pytest actions:
1. unit
2. integrative
The integrative tests are naively chunked at the moment between `integrative-1` and integrative-2`
I think there should be an issue ticket created to rewrite some tests to be folderpath agnostic. If you have filename collision issues, they can be solved by other means. The benefit can be gained when you run parallel test workers. See how the unit test differs, whereas the integrative tests will be run sequentially if we use `integrative_batch_tests.sh`. I think this will make a difference since the integration tests take about 29m  :grimacing: 
Once you merge this, you should get builds for every commit. I think it might make sense to at least have unit tests be a required step before merging. 
I am happy to guide you through those GitHub …

Add pytest CI (Github Actions)

---

Makefile

I was encountering the following error when running on a machine without a GPU:
```
docker run -p 8080:8080 \
--gpus all \
--hostname job-Gq8JzK80Zv77jJQFFzPBvY6Q.dnanexus.cloud \
--privileged \
-v /home/dnanexus/AMPL/../work/:/work/ kartstig/ampl:cpu-pfda \
/bin/bash -l -c "jupyter-notebook --ip=0.0.0.0 --no-browser --allow-root --port=8080"
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request: unknown.
ERRO[0001] error waiting for container:                 
make: *** [Makefile:73: jupyter-notebook] Error 125 …
```

Only add gpus if platform is set

---

Makefile
pip/cpu_requirements.txt

- Updates a bug with the GPU_ARG when running GPU with docker
- Loosens up dependency for tensorflow for `arm64` builds
- Relates to https://github.com/ATOMScience-org/AMPL/pull/365

Makefile updates

---

.github/workflows/pytest.yml
Makefile

- Adds the MODAC unit tests to run on Github Actions
- Fixes https://github.com/mass-matrix/AMPL/issues/66
I had to wait for the changes in `1.6.3` with all the Github Actions code for this to go in, but it's ready now :tada:

Ensure modac tests are run

---

.github/workflows/pytest.yml
Makefile
atomsci/ddm/test/integrative/integrative_batch_chunk_tests

I was able to verify the output by running the unit tests locally

Use cov module instead of folder path

---

atomsci/ddm/test/unit/test_compute_drug_likeness.py
atomsci/ddm/utils/rdkit_easy.py

Add a function to the rdkit_easy module to compute various drug-likeness criteria for compounds in a data frame (Lipinski rule of 5, Ghose and Veber filters, QED), along with the descriptors used to derive them.

Add compute_drug_likeness function to rdkit_easy

---

atomsci/ddm/pipeline/predict_from_model.py
atomsci/ddm/test/integrative/external_dataset/H1_graphconv.json
atomsci/ddm/test/integrative/external_dataset/test_external_dataset.py

The external_training_data parameter in `predict_from_model.predict_from_model_file` was unused because it updated `model_pipeline.param` when model_pipeline uses `model_pipeline.orig_param` to load the dataset used to calculate AD indexes.

external_training_data parameter was unused
